# vim: set sw=2 ts=2 softtabstop=2 expandtab:
language: csharp
dist: bionic
sudo: true
dotnet: 3.1
mono: none
git:
  depth: false
env:
  global:
    - SOLUTION=Source/Boogie-NetCore.sln
    - Z3URL=https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
  matrix:
    - CONFIGURATION=Debug
    - CONFIGURATION=Release
install:
  # Download a Z3 release
  - wget ${Z3URL}
  - unzip z3*.zip
  - export PATH="$(find $PWD/z3* -name bin -type d):$PATH"
  # Install needed python tools
  - sudo pip install lit OutputCheck pyyaml
script:
  - dotnet build -c ${CONFIGURATION} ${SOLUTION}
  - dotnet test --no-build -c ${CONFIGURATION} ${SOLUTION}
  - lit -v -D dotnet -D configuration=${CONFIGURATION} Test
deploy:
  - provider: script
    script:
      - dotnet nuget push Source/BoogieDriver/bin/${CONFIGURATION}/Boogie*.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: ${CONFIGURATION}=Release
  - provider: releases
    api_key: TODO
    file_glob: true
    file: Source/BoogieDriver/bin/${CONFIGURATION}/Boogie*.nupkg
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: ${CONFIGURATION}=Release
